### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bnhn**
Added wekan.io, a trello-like collaboration platform

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@bnhn Please rewrite your commit to be something like "Add Wekan Source Code" . Then resolve merge conflicts so that your PR can be mergeable.

**Comment by unicodeveloper** [comment]
What's the latest on this @bnhn

**Comment by bnhn** [comment]
@unicodeveloper I completely missed that email, let me get right on to it.

**Comment by unicodeveloper** [comment]
I'll appreciate that @bnhn

**Pull request closed without merging**
